# Generated by Django 4.0 on 2024-10-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_blog_options_blog_video_alter_blog_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelpost',
            options={'verbose_name_plural': 'Models'},
        ),
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name_plural': 'Tutorials'},
        ),
        migrations.AddField(
            model_name='modelpost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='models/videos/'),
        ),
        migrations.AddField(
            model_name='tutorial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='tutorials/videos/'),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tutorials/'),
        ),
    ]
