# Generated by Django 4.0 on 2024-10-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_modelpost_options_alter_tutorial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='downloads/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='downloads/videos/')),
                ('file', models.FileField(upload_to='downloads/files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Downloadable Apps',
            },
        ),
    ]
