# Generated by Django 4.0 on 2024-10-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_downloadableapp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadableapp',
            options={},
        ),
    ]
